index/urls.py
from django.urls import include, path
from .views import index

urlpatterns = [
    path('', index, name='index'),
    #path('Sign in/', signin, name = 'Sign in'),
    #path('Sign up/', signup, name='Sign up'),
]

regist/urls.py
from django.conf.urls import url
from regist import views

app_name = 'regist'

urlpatterns=[
    url(r'^register/$', views.register,name='register'),
    url(r'^user_login/$', views.user_login,name='user_login'),
]

reuse_me/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from regist import views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index, name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^regist/',include('regist.urls')),
    url(r'^logout/$',views.user_logout,name='logout'),
]

index/models.py
from django.db import models

# Create your models here.

regist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo (models.Model) :

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    portofolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pic', blank = True)

    def __str__(self) :
        return self.user.username

regist/forms.py
from django import forms
from regist.models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
 password = forms.CharField(widget=forms.PasswordInput())

 class Meta():
  model = User
  fields = ('username','password','email')

class UserProfileInfoForm(forms.ModelForm):

 class Meta():
  model = UserProfileInfo
  fields = ('portofolio_site','profile_pic')

index/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    response = {}
    return render(request, 'index.html', response)

regist/views.py
from django.shortcuts import render
from regist.forms import UserForm, UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request) :
    return render(request, 'regist/index.html')

def special(request):
    return HttpResponse("You are logged in !")

def user_logout (request) :
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == 'POST' :
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES :
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else :
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'regist/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request) :
    if request.method == 'POST' :
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed")
            print("They used usernmae : {} and password : {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'regist/login.html', {})

index/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
        <link rel="stylesheet" href="{% static "css/style.css" %}">
        <script src="main.js"></script>
        <link rel="stylesheet" type="text/css" media="screen" href="base.css" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />

    </head>
    <body>
      <header>
        {% include "header.html" %}
      </header>

        {% block mantap %}
        {% endblock %}
        {% include "footer.html" %}
    </body>
</html>

index/templates/footer.html
<footer>
    <div>
        Ini Footer    
    </div>
</footer>

index/templates/header.html
  <nav class = "navbar navbar-style">
<div class ="container">
  <div class = "navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#micon">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
    {% load static %}
    <img class = "logo"  src = "{% static "images/logo.png" %}" alt = "logo"/>
  </div>
  <div class="collapse navbar-collapse" id="micon">

  <ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'index' %}">Home</a></li>
    <li><a href="">Sign in</a></li>
    <li><a href="">Sign up</a></li>
  </ul>
</div>
</div>
</nav>

index/templates/index.html
{% extends "base.html" %}
{% block title %}Welcome to Reuse-Me{% endblock %}
{% load staticfiles %}
<body>

  {% block mantap %}
<div>
    <div class = "boxed">
    <div class = "container">
      <h2> Category </h2>
    <div class = "row">
    <div class = "col-md-3">

    <div class = "category">
        {% load static %}
        <img class = "gambar" src = "{% static "images/galaxy.png" %}" class = "img-responsive">
        <div class ="overlay">
          <button type = "button" class="btn btn-secondary" title="Phone" align="right"> </button>
          </div>

          <div>

          <h3> Smartphone </h3>
          </div>
      </div>
      </div>

      <div class = "col-md-3">
      <div class = "category">
          {% load static %}
          <img class = "gambar" src = "{% static "images/baju.png" %}" class = "img-responsive">
          <div class ="overlay">
            <button type = "button" class="btn btn-secondary" title="clothes" align="right"> </button>
            </div>

              <div>
                <h3> Clothes </h3>
                </div>


        </div>
        </div>

        <div class = "col-md-3">
        <div class = "category">
            {% load static %}
            <img class = "gambar" src = "{% static "images/kacamata.png" %}" class = "img-responsive">
            <div class ="overlay">
              <button type = "button" class="btn btn-secondary" title="accesories" align="right"> </button>
              </div>

              <div>
                <h3> Accesories </h3>
                </div>



          </div>
          </div>

        <div class = "col-md-3">
        <div class = "category">
            {% load static %}
            <img class = "gambar" src = "{% static "images/basket.png" %}" class = "img-responsive">
            <div class ="overlay">
              <button type = "button" class="btn btn-secondary" title="hobby" align="right"> </button>
              </div>

              <div>

              <h3> Hobby </h3>
              </div>

          </div>
          </div>
          </div>


      </div>
      </div>
</div>

  {% endblock%}
</body>

templates/regist/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset = "utf-8" >
    <title> Base </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    </head>
      <body>
        <nav class="navbar navbar-default navbar-static-top">
          <div class="container">
            <ul class="nav navbar-nav">
              <li><a class="navbar-brand" href="{% url 'index'%}"> </a> DJANGO </li>
              <li><a class="navbar-link" href="{% url 'admin:index'%}"> </a> Admin </li>
              <li><a class="navbar-link" href="{% url 'regist:register'%}">Register</a></li>
              {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}"> Logout</a></li>
                {%else%}
                <li><a class="navbar-link" href="{% url 'regist:user_login' %}">Login</a></li>
                {%endif%}

              </ul>
              </div>
              </nav>

              <div class="container">
                {% block body_block %}
                {% endblock %}
                </div>
                </body>
                </html>

templates/regist/index.html
{% extends "regist/base.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>Welcome to Reuse-me !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>

{% endblock %}

templates/regist/login.html
{% extends 'regist/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>

  <form method="post" action=" {% url 'regist:user_login' %}">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Username">

  <labe_for="password">Password:</label>
    <input type="password" name="password"
    placeholder="Password">

    <input type="submit" name="" value="Login">

    </form>

    </div>
      </div>
    {% endblock %}

templates/regist/registration.html
{% extends "regist/base.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1> Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

  <form enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    {{ user_form.as_p}}
    {{ profile_form.as_p}}
    <input type="submit" name="" value="Register">
    </form>

    {% endif %}
  </div>
  </div>
{% endblock %}